-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 27, 2019 at 02:48 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zxtnhezr_realsource`
--

--
-- Dumping data for table `blog_posts`
--

INSERT INTO `blog_posts` (`id`, `title`, `headline`, `body`, `user_id`, `cover_image`, `created_at`, `updated_at`) VALUES
(1, 'Simplified Approach To Tertiary Education', 'Assignment Support Plan', '<p>This start-up company was founded out of a desire to simplify the learning experience by providing models for academic papers and providing mental health support plan to neutralize the crippling effects of a demanding academic programme. To demystify the language of academic writing at a higher level of education. Be it an originally written paper, research proposal, writing enhancement, editing or mental health lifestyle plan, realsource.co.za pledges to transform the very principle of how education is administered.</p>\r\n\r\n<h2>Transition: Secondary to Tertiary</h2>\r\n\r\n<p>Academic writing is comparable to learning a new language. From the format to the tone, to the referencing, this language can seem foreign at first. Hence, we provide means to speed up the acclimatization of new students to the higher learning world. Much like seeing a CV of your mentor so to create your own CV, model papers that we provide are a great way to seamlessly tap into the world of academic writing.</p>\r\n\r\n<h2>Deadline: Demanding Academic Programme</h2>\r\n\r\n<p>In a university space, it is not uncommon to have multiple deadlines and little time. Hence, realsource.co.za is an extra brain to be used to reduce the burden on your shoulders. This way, you can channel your attention and effort to a manageable workload. This allows you to play the game of quality and not quantity.</p>\r\n\r\n<h2>Mental Health: Lifestyle Goals</h2>\r\n\r\n<p>Depression, Stress, and Homesickness, are common mental health challenges at a university space. In addition to academic papers, research proposal, writing enhancement and editing, realsource.co.za also provides a simple mental health plan to alleviate the emotional and psychological hazards of being a student in the 21<sup>st</sup> Century. This comes in the form of morning yoga and meditation hosted by our vibrant personalities to rebalance your chemical energies.</p>\r\n\r\n<a href=\"#\"><img alt=\"\" src=\"https://source.unsplash.com/random/?fun\" /> </a>\r\n\r\n<span class=\"caption text-muted\">The dreams of yesterday are the hopes of today and the reality of tomorrow.</span>\r\n\r\n<h2>Why realsource.co.za</h2>\r\n\r\n<ul>\r\n	<li>We meet any deadline. Days or hours.</li>\r\n	<li>We reduce the burden on your shoulders.</li>\r\n	<li>We do guarantee you an awesome pass mark.</li>\r\n	<li>We do have a refund policy.</li>\r\n	<li>We do help you better manage your academic affairs.</li>\r\n	<li>We do Include a Thesis Statement in the Introduction.</li>\r\n	<li>We do Use Transitions Between Paragraphs.</li>\r\n	<li>We do Cite Examples.</li>\r\n	<li>We do Discuss Literature in the Present Tense.</li>\r\n	<li>We do Use Advanced Vocabulary.</li>\r\n	<li>We do Respond to the Prompt of the Essay.</li>\r\n	<li>We do Use Simple Sentences.</li>\r\n</ul>', 2, 'happy black couple_1553783453.jpg', '2019-03-26 04:45:04', '2019-03-29 07:03:37'),
(17, 'We\'re Uber For Student Assignments', 'Assignment Rough Drafts That Are Submission-Ready', '<p>We provide assignment drafts in all faculties as well as all varsities. The assignments we provide are originally written for the client by a Freelance Research Writer, a graduate in the body of knowledge in question. For each client, the assignment is quality-controlled by contracted tutors in the field of study.&nbsp;</p>\r\n\r\n<p>The assignment comes to the client submission-ready.&nbsp;</p>\r\n\r\n<p>Each assignment is uniquely crafted for a specific client. To this effect, we do not recycle assignments. As such, we are plagiarism-free.&nbsp;</p>\r\n\r\n<p>We allocate each client their personalfFreelance graduate who will conduct the research and write the assignment, while keeping the client updated about the progress of the paper, much like Uber for your assignment, if not your degree.&nbsp;</p>\r\n\r\n<p>Price per page starts at R30 and factors in the deadline, like booking a flight. Naturally, short notice will be associated with time pressure, hence we provide you with convenience.&nbsp;</p>\r\n\r\n<p>For the sake of maintaining the integrity of the learning process, by a code of ethics, we are of the standpoint that our clients should consider to paraphrase, rewrite, restructure and learn the concepts of the assignment content, before submission, so to enjoy a simplified learning experience while keeping the reading sources from the research we provide.&nbsp;</p>', 2, 'happy black couple_1553785170.jpg', '2019-03-28 08:59:30', '2019-03-28 11:42:37'),
(18, 'Mission Statement', 'Homework Support 24/7', '<p>We are an educational and emotional intelligence institution.</p>\r\n\r\n<p>We are here to simplify the learning experience.</p>\r\n\r\n<p>Our mission is to use the power of the 4th Industrial Revolution to provide educational and emotional support to students across the continent. We mean to enable students to simplify&nbsp;their learning experience by meeting their educational and emotional needs. We guarantee that every student&nbsp;can get&nbsp;tailored homework help in any subject 24/7 as well as emotional support.</p>\r\n\r\n<h2 class=\"section-heading\">WHAT DO WE DO</h2>\r\n\r\n<ul>\r\n	<li>We aim to help students manage the crippling effects of a demanding academic project on their emotional wellness.</li>\r\n	<li>We provide originally written essays in any subject, affordably and efficiently.</li>\r\n	<li>We bring to you a network of certified academic staff to help with any assignment any time of the day.</li>\r\n	<li>We bring to you a mental health lifestyle plan to reduce the emotional burden of being a student.</li>\r\n</ul>', 2, 'noimage.jpg', '2019-03-28 09:07:37', '2019-03-29 07:55:19'),
(19, 'Being A Freelance Research Writer Is Simple And Very Rewarding.', 'Earn R1000 - R5000 Writing Model Papers For Students', '<h2 class=\"section-heading\">Why Should I join?</h2>\r\n\r\n<ol>\r\n	<li>A variety of topics and courses, plus personal development.</li>\r\n	<li>Rewarding salary, R1000 - R5000 per week.</li>\r\n	<li>Flexible schedule, you decide when and how much you would write.</li>\r\n	<li>Manage your workload on-the-go with our online based company.</li>\r\n</ol>\r\n\r\n<h2 class=\"section-heading\">FAQ</h2>\r\n\r\n<h3>APPLICATION</h3>\r\n\r\n<ol>\r\n	<li><strong>What are the requirements for Freelance Research Writer?</strong><br />\r\n	<span class=\"marker\">Yes</span>, only one. Willingness to roll up your sleeves. So, if have some form of University education and have a neck for research, writing, grammar and&nbsp;working independently, then the job is yours - welcome on board.</li>\r\n	<li><strong>What should I do to start working and earning?</strong><br />\r\n	Apply on our website by&nbsp;sending us a message or WhatsApp your full name and University qualifications to 076 592 4655.&nbsp;You will receive quick training and start working and earning.</li>\r\n</ol>\r\n\r\n<h3>Paid&nbsp;GIGS</h3>\r\n\r\n<ol>\r\n	<li><strong>What kind of assignments will I research and write?&nbsp;</strong><br />\r\n	Our paid gigs usually include essay writing, research papers, literature reviews, analytical papers, law judgement opinions, etc.&nbsp;</li>\r\n	<li><strong>What courses or modules I do?</strong><br />\r\n	We have paid gigs on different subjects: humanities, commerce, social sciences, natural sciences, formal sciences/ Most of them are humanities. You can make your&nbsp; choice based on your field of expertise, deadline, interest, etc.</li>\r\n	<li><strong>How do I get paid?</strong><br />\r\n	After selection to become Freelance Research Writer, you will get access to the ordering system where you will receive notifications about available paid gigs. It is a classical freelance platform with an open market. You can manage your workload at&nbsp;your own discretion.&nbsp;</li>\r\n</ol>\r\n\r\n<h3>PAYMENT INFO</h3>\r\n\r\n<ol>\r\n	<li><strong>What is an average payment per writing work?</strong><br />\r\n	Payment per gig depends on the number of pages, deadline, and academic level. Earnings per week vary around R1000 - R5000.</li>\r\n	<li><strong>How often do I get paid? </strong><br />\r\n	You will receive your payment twice per month, on the 1st and the 15th, depending on the number of essays you will have succussfully completed.&nbsp;</li>\r\n</ol>', 2, 'noimage.jpg', '2019-03-28 10:04:58', '2019-03-29 07:55:01'),
(20, 'Price For An Assignment', 'From R30 Per Page', '<p>The prices are per page. A page is an average of 350 words at 12-point font size and 1.5 spacing.&nbsp;</p>\r\n\r\n<h2>Deadline Price per page</h2>\r\n\r\n<table cellspacing=\"0\" class=\"display table table-bordered\" id=\"price_table\" style=\"width:100%\">\r\n	<thead>\r\n		<tr>\r\n			<th>Due Date</th>\r\n			<th>Price Per Page</th>\r\n		</tr>\r\n	</thead>\r\n	<tfoot>\r\n		<tr>\r\n			<th>Due Date</th>\r\n			<th>Price Per Page</th>\r\n		</tr>\r\n	</tfoot>\r\n	<tbody>\r\n		<tr>\r\n			<td style=\"text-align:center\">10 days</td>\r\n			<td style=\"text-align:center\">R30</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">9 days</td>\r\n			<td style=\"text-align:center\">R35</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">8 Days</td>\r\n			<td style=\"text-align:center\">R40</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">7 Days</td>\r\n			<td style=\"text-align:center\">R45</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">6 Days</td>\r\n			<td style=\"text-align:center\">R50</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">5 Days</td>\r\n			<td style=\"text-align:center\">R60</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">4 Days</td>\r\n			<td style=\"text-align:center\">R70</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">3 Days</td>\r\n			<td style=\"text-align:center\">R80</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">48 Hours</td>\r\n			<td style=\"text-align:center\">R95</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">24 Hours</td>\r\n			<td style=\"text-align:center\">R100</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">12 Hours</td>\r\n			<td style=\"text-align:center\">R180</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">6 Hours</td>\r\n			<td style=\"text-align:center\">R250</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=\"text-align:center\">3 Hours</td>\r\n			<td style=\"text-align:center\">R350</td>\r\n		</tr>\r\n	</tbody>\r\n</table>', 2, 'noimage.jpg', '2019-03-28 12:39:19', '2019-03-29 06:46:48'),
(21, 'Welcome', 'Learning Experience Simplified', '<p>Hello.</p>\r\n\r\n<p>Welcome to Learning Simplified.&nbsp;</p>\r\n\r\n<p>We bring to you three services:</p>\r\n\r\n<ol>\r\n	<li>Full tailored&nbsp;written&nbsp;essays and assignments that are ready for submission.&nbsp;</li>\r\n	<li>Research proposals, proof-reading, editing and a free and updated past paper database.</li>\r\n	<li>Mental Health Lifestyle Plan to help you better manage the crippling effects of a demanding academic programme.</li>\r\n</ol>\r\n\r\n<p>We bring to you these three services because we recognize value in unlocking means to help you better manage your academic career and mental health, without neglecting one for the other.&nbsp;</p>\r\n\r\n<p>We introduce with the perception that the future of education is online, as the 4th Industrial Revolution is upon our world, hence we are available via website, email, WhatsApp, Facebook, Instagram and Twitter. This easy access is so we can listen to you and better meet your needs.&nbsp;</p>', 2, 'hout model_1553798905.jpg', '2019-03-28 12:48:26', '2019-04-20 00:30:46');

--
-- Dumping data for table `migrations`
--


--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Nkosingiphile Sibandze', 'nkosi@realsource.co.za', NULL, '$2y$10$eygNtTNBsX6IZ8cYThHelOQIMis9BFkGI8r2Hyk/Cv53O/sQ7KG4i', 'kMFO0aw1nxnlZJ21XtW67KMsdVnZwUks6vFqzufY2CMf60EZODWPSEclIHSF', '2019-03-26 03:56:18', '2019-03-26 03:56:18'),
(2, 'Jonas M. Maepa', 'jonas.maepa@realsource.co.za', NULL, '$2y$10$XHl82EP5CjYSTxY1wzLsJOqOLtb9r8BKw71pKvy/KGa/5EwfTYTWG', 'xNFNpRM23ArbeOkXsxGChIBjjfxJE0pnBVkb9TpvlxWkqzYu0SQlwvcmwtXu', '2019-03-26 03:57:42', '2019-03-26 03:57:42');

--
-- Dumping data for table `writing_levels`
--

INSERT INTO `writing_levels` (`id`, `name`, `purpose`, `created_at`, `updated_at`) VALUES
(1, 'High School', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(2, '1st year', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(3, '2nd Year', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(4, '3rd Year', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(5, '4th/Honors Year', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(6, 'Masters', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(7, 'PhD', 1, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(8, 'Standard', 2, '2019-04-25 18:00:00', '2019-04-25 18:00:00'),
(9, 'Premium', 2, '2019-04-25 18:00:00', '2019-04-25 18:00:00');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
